name: Flask CI/CD Pipeline

on:
  push:
    branches: [ "Feature/server-part-init", "Feature/PDFValidation" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.12.2
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.2

    - name: Set image tag in environment file
      run: echo "IMAGE_TAG=baszarinhi9816/corvuscoraxtest:latest" >> $GITHUB_ENV  
    
    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: ${{ env.IMAGE_TAG }}
        
        #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
#TODO other tests
